modLoader = "javafml"
loaderVersion = "[37,)"
#issueTrackerURL = ""
license = "Custom"

[[mods]]
modId = "biomemakeover"
version = "${version}"
displayName = "Biome Makeover"
authors = "LASERKNIGHTS"
description = '''
Biome Makeover is a mod designed to update vanilla's biomes.
'''
logoFile = "bm-logo.png"

[[dependencies.biomemakeover]]
modId = "forge"
mandatory = true
versionRange = "[41.0.22,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.biomemakeover]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.biomemakeover]]
modId = "architectury"
mandatory = true
versionRange = "[5.8.29,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.biomemakeover]]
modId = "taniwha"
mandatory = true
versionRange = "[1.19.4-4.0.0,)"
ordering = "AFTER"
side = "BOTH"